In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("/content/Employee_Dataset.csv")

In [3]:
data.head(5)

         Name  Age  Salary Gender    City   Mood
0  Employee_1   59  142719      F    Pune  Happy
1  Employee_2   49   50234      F  Nagpur    Sad
2  Employee_3   35   51381      F  Nagpur  Happy
3  Employee_4   28   47274      F   Delhi    Sad
4  Employee_5   41  142162      F  Nagpur    Sad

In [4]:
data.tail(5)

                Name  Age  Salary Gender    City   Mood
9995   Employee_9996   44   52152      F  Mumbai  Happy
9996   Employee_9997   33  114738      F    Pune    Sad
9997   Employee_9998   49   56445      M    Pune  Happy
9998   Employee_9999   52  106688      M  Nashik    Sad
9999  Employee_10000   44  101153      F  Mumbai  Happy

In [11]:
data['Gender'].value_counts(['M'])

Gender
F    0.5043
M    0.4957
Name: proportion, dtype: float64

                Name  Age  Salary Gender    City   Mood
0         Employee_1   59  142719      F    Pune  Happy
1         Employee_2   49   50234      F  Nagpur    Sad
2         Employee_3   35   51381      F  Nagpur  Happy
3         Employee_4   28   47274      F   Delhi    Sad
4         Employee_5   41  142162      F  Nagpur    Sad
...              ...  ...     ...    ...     ...    ...
9995   Employee_9996   44   52152      F  Mumbai  Happy
9996   Employee_9997   33  114738      F    Pune    Sad
9997   Employee_9998   49   56445      M    Pune  Happy
9998   Employee_9999   52  106688      M  Nashik    Sad
9999  Employee_10000   44  101153      F  Mumbai  Happy

[10000 rows x 6 columns]

In [15]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler,OneHotEncoder

In [24]:
ct=ColumnTransformer(
    transformers=[
        ['num',StandardScaler(),['Age','Salary']],
        ["cat",OneHotEncoder(),['Gender','City']]
    ],
    remainder='passthrough'
)

In [25]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[['num', StandardScaler(), ['Age', 'Salary']],
                                ['cat', OneHotEncoder(), ['Gender', 'City']]])

In [27]:
X_transformed = ct.fit_transform(data[['Salary', 'Age', 'City','Gender']])

In [28]:
X_transformed

array([[ 1.69408714,  1.54153462,  1.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 0.79951495, -1.11805389,  1.        , ...,  1.        ,
         0.        ,  0.        ],
       [-0.45288612, -1.08506964,  1.        , ...,  1.        ,
         0.        ,  0.        ],
       ...,
       [ 0.79951495, -0.93944434,  0.        , ...,  0.        ,
         0.        ,  1.        ],
       [ 1.06788661,  0.50539218,  0.        , ...,  0.        ,
         1.        ,  0.        ],
       [ 0.35222885,  0.34622234,  1.        , ...,  0.        ,
         0.        ,  0.        ]])

In [29]:
pipe=

                Name  Age  Salary Gender    City   Mood
0         Employee_1   59  142719      F    Pune  Happy
1         Employee_2   49   50234      F  Nagpur    Sad
2         Employee_3   35   51381      F  Nagpur  Happy
3         Employee_4   28   47274      F   Delhi    Sad
4         Employee_5   41  142162      F  Nagpur    Sad
...              ...  ...     ...    ...     ...    ...
9995   Employee_9996   44   52152      F  Mumbai  Happy
9996   Employee_9997   33  114738      F    Pune    Sad
9997   Employee_9998   49   56445      M    Pune  Happy
9998   Employee_9999   52  106688      M  Nashik    Sad
9999  Employee_10000   44  101153      F  Mumbai  Happy

[10000 rows x 6 columns]